from tkinter import *
root = Tk()
# root.geometry("500x500")
root.title("Calculator")
# root.rowconfigure(0,weight=1)
k = Label(text="", font=("Agency FB",50))
k.grid(row=1, column=0)
dis = Label(root, text="Display" , font=("Segoe UI", 20), relief=RAISED, bd=5, padx=10, pady=10 )
dis.place(x=0, y=0)

button1 = Button(root, text="1", font=("Segoe UI", 20))
button1.grid(row=2, column=0)
button2 = Button(root, text="2", font=("Segoe UI", 20))
button2.grid(row=2, column=1)
button3 = Button(root, text="3", font=("Segoe UI", 20))
button3.grid(row=2, column=2)
buttonadd = Button(root, text=" + ", font=("Segoe UI", 22))
buttonadd.grid(row=2, column=3)
button4 = Button(root, text="4", font=("Segoe UI", 20))
button4.grid(row=3, column=0)
button5 = Button(root, text="5", font=("Segoe UI", 20))
button5.grid(row=3, column=1)
button6 = Button(root, text="6", font=("Segoe UI", 20))
button6.grid(row=3, column=2)
buttonminus = Button(root, text=" - ", font=("Segoe UI", 23))
buttonminus.grid(row=3, column=3)
button7 = Button(root, text="7", font=("Segoe UI", 20))
button7.grid(row=4, column=0)
button8 = Button(root, text="8", font=("Segoe UI", 20))
button8.grid(row=4, column=1)
button9 = Button(root, text="9", font=("Segoe UI", 20))
button9.grid(row=4, column=2)
buttonmul = Button(root, text=" x ", font=("Segoe UI", 22))
buttonmul.grid(row=4, column=3)
buttoncl = Button(root, text="C", font=("Segoe UI", 20))
buttoncl.grid(row=5, column=0)
button0 = Button(root, text="0", font=("Segoe UI", 20))
button0.grid(row=5, column=1)
buttondiv = Button(root, text="÷", font=("Segoe UI", 20))
buttondiv.grid(row=5, column=2)


root.mainloop()

