from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import *
from YT_downloader_module import *
from tkinter import filedialog as fd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 732)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../OneDrive/Pictures/Icons/YouTube_downloader.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(44, 48, 56);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Heading = QtWidgets.QLabel(self.centralwidget)
        self.Heading.setGeometry(QtCore.QRect(10, 10, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Heading.setFont(font)
        self.Heading.setStyleSheet("color: rgb(34, 255, 255);")
        self.Heading.setObjectName("Heading")
        self.Link_label = QtWidgets.QLabel(self.centralwidget)
        self.Link_label.setGeometry(QtCore.QRect(20, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.Link_label.setFont(font)
        self.Link_label.setStyleSheet("color: rgb(34, 255, 255);")
        self.Link_label.setObjectName("Link_label")
        self.Dir_label = QtWidgets.QLabel(self.centralwidget)
        self.Dir_label.setGeometry(QtCore.QRect(20, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.Dir_label.setFont(font)
        self.Dir_label.setStyleSheet("color: rgb(34, 255, 255);")
        self.Dir_label.setObjectName("Dir_label")
        self.L_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.L_entry.setGeometry(QtCore.QRect(20, 160, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_entry.setFont(font)
        self.L_entry.setStyleSheet("color: rgb(34, 255, 255);")
        self.L_entry.setFrame(True)
        self.L_entry.setObjectName("L_entry")
        self.Dir_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.Dir_entry.setGeometry(QtCore.QRect(20, 280, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Dir_entry.setFont(font)
        self.Dir_entry.setStyleSheet("color: rgb(34, 255, 255);")
        self.Dir_entry.setFrame(True)
        self.Dir_entry.setObjectName("Dir_entry")
        self.Vid_title = QtWidgets.QLabel(self.centralwidget)
        self.Vid_title.setGeometry(QtCore.QRect(20, 380, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.Vid_title.setFont(font)
        self.Vid_title.setStyleSheet("color: rgb(34, 255, 255);")
        self.Vid_title.setObjectName("Vid_title")
        self.Vid_Length = QtWidgets.QLabel(self.centralwidget)
        self.Vid_Length.setGeometry(QtCore.QRect(20, 340, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.Vid_Length.setFont(font)
        self.Vid_Length.setStyleSheet("color: rgb(34, 255, 255);")
        self.Vid_Length.setObjectName("Vid_Length")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 640, 621, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("color: rgb(34, 255, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.Download_button = QtWidgets.QPushButton(self.centralwidget)
        self.Download_button.setGeometry(QtCore.QRect(250, 540, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.Download_button.setFont(font)
        self.Download_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Download_button.setStyleSheet("color: rgb(34, 255, 255);")
        icon = QtGui.QIcon.fromTheme("1")
        self.Download_button.setIcon(icon)
        self.Download_button.setIconSize(QtCore.QSize(20, 30))
        self.Download_button.setAutoDefault(False)
        self.Download_button.setDefault(False)
        self.Download_button.setFlat(False)
        self.Download_button.setObjectName("Download_button")
        self.Dir_go = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.show_info())
        self.Dir_go.setGeometry(QtCore.QRect(440, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.Dir_go.setFont(font)
        self.Dir_go.setStyleSheet("color: rgb(34, 255, 255);")
        self.Dir_go.setFlat(False)
        self.Dir_go.setObjectName("Dir_go")
        self.link_go = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.show_info())
        self.link_go.setEnabled(True)
        self.link_go.setGeometry(QtCore.QRect(440, 160, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.link_go.setFont(font)
        self.link_go.setAcceptDrops(False)
        self.link_go.setAutoFillBackground(False)
        self.link_go.setStyleSheet("color: rgb(34, 255, 255);")
        self.link_go.setCheckable(False)
        self.link_go.setFlat(False)
        self.link_go.setObjectName("link_go")
        self.Quality_box = QtWidgets.QComboBox(self.centralwidget)
        self.Quality_box.setGeometry(QtCore.QRect(400, 540, 73, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Quality_box.setFont(font)
        self.Quality_box.setStyleSheet("color: rgb(34, 255, 255);")
        self.Quality_box.setEditable(False)
        self.Quality_box.setFrame(True)
        self.Quality_box.setObjectName("Quality_box")
        self.L_ChName = QtWidgets.QLabel(self.centralwidget)
        self.L_ChName.setGeometry(QtCore.QRect(20, 420, 631, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.L_ChName.setFont(font)
        self.L_ChName.setStyleSheet("color: rgb(34, 255, 255);")
        self.L_ChName.setObjectName("L_ChName")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YT Downloader"))
        self.Heading.setText(_translate("MainWindow", "YouTube Downloader"))
        self.Link_label.setText(_translate("MainWindow", "Enter link:"))
        self.Dir_label.setText(_translate("MainWindow", "Enter Directory:"))
        self.Vid_title.setText(_translate("MainWindow", "Video title: "))
        self.Vid_Length.setText(_translate("MainWindow", "Video Length: "))
        self.Download_button.setText(_translate("MainWindow", "Download"))
        self.Dir_go.setText(_translate("MainWindow", "Browse.."))
        self.link_go.setText(_translate("MainWindow", "GO"))
        self.L_ChName.setText(_translate("MainWindow", "Channel name:"))

    def show_info(self):
        link = self.L_entry.text()
        yt = YouTube(link)
        self.Vid_title.setText(f'Video title: {yt.title}')
        self.Vid_Length.setText(f'Video Length: {round(yt.length/60,2)} min')
        ch = Channel(yt.channel_url)
        self.L_ChName.setText(f'Channel name:{ch.channel_name}')

    def getdir(self):
        global path
        path = fd.askdirectory()
        self.Dir_entry.setText(f'{path}')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
